services:
  account-monitor:
    image: ghcr.io/ktl-xv/account-monitor
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - ./accounts.example.yaml:/accounts.yaml
    environment:
      NTFY_TOKEN: ${NTFY_TOKEN}
      NTFY_URL: ${NTFY_URL}
      NTFY_TOPIC: ${NTFY_TOPIC}
      STATIC_ACCOUNTS_PATH: /accounts.yaml
      CHAINS: ETHEREUM,ARBITRUM

      CHAIN_RPC_ETHEREUM: https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
      CHAIN_NAME_ETHEREUM: Mainnet
      CHAIN_BLOCKTME_ETHEREUM: 12000
      CHAIN_SPAM_FILTER_LEVEL_ETHEREUM: None
      CHAIN_EXPLORER_ETHEREUM: https://etherscan.io
      CHAIN_ID_ETHEREUM: 1

      CHAIN_RPC_ARBITRUM: https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
      CHAIN_NAME_ARBITRUM: Arbitrum
      CHAIN_BLOCKTME_ARBITRUM: 5000
      CHAIN_MODE_ARBITRUM: Events
      CHAIN_EXPLORER_ARBITRUM: https://arbiscan.io
      CHAIN_ID_ARBITRUM: 42161
