name: Build and push image

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=web

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: git.ktlxv.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_GITEA_REPO_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: git.ktlxv.com/jorge/account-monitor
