name: Build and push image

on:
  push:
    branches:
      - main
      - debug/*

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=web

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: git.ktlxv.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_GITEA_REPO_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: git.ktlxv.com/jorge/account-monitor
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch,enable={{#if is_default_branch}}false{{else}}true{{/if}}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
